## Load MNIST on Python 3.x

In [1]:
import pickle
import gzip
import numpy as np

In [2]:
filename = 'mnist.pkl.gz'
f = gzip.open(filename, 'rb')
training_data, validation_data, testing_data = pickle.load(f, encoding='latin1')

train_data=np.array(training_data[0])
train_target=np.array(training_data[1])
valid_data=np.array(validation_data[0])
valid_target=np.array(validation_data[1])
test_data=np.array(testing_data[0])
test_target=np.array(testing_data[1])

print(train_data.shape)
print(valid_data.shape)
print(test_data.shape)

print(train_target.shape)
print(valid_target.shape)
print(test_target.shape)
f.close()

(50000, 784)
(10000, 784)
(10000, 784)
(50000,)
(10000,)
(10000,)


## Load USPS on Python 3.x

In [3]:
from PIL import Image
import os


In [4]:
USPSMat  = []
USPSTar  = []
curPath  = 'USPSdata/Numerals'
savedImg = []

for j in range(0,10):
    curFolderPath = curPath + '/' + str(j)
    imgs =  os.listdir(curFolderPath)
    for img in imgs:
        curImg = curFolderPath + '/' + img
        if curImg[-3:] == 'png':
            img = Image.open(curImg,'r')
            img = img.resize((28, 28))
            savedImg = img
            imgdata = (255-np.array(img.getdata()))/255
            USPSMat.append(imgdata)
            USPSTar.append(j)
print(np.array(USPSMat).shape)
print(np.array(USPSTar).shape)
USPS_data=np.array(USPSMat)
USPS_Target=np.array(USPSTar)

(19999, 784)
(19999,)


In [6]:
#SVM

from sklearn import datasets, svm, metrics

classifier = svm.SVC(C=200,kernel='linear',gamma=0.05)
classifier.fit(train_data,train_target)


SVC(C=200, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.05, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [7]:
y_pred_svm = classifier.predict(test_data)

In [11]:
usps_pred_svm = classifier.predict(USPS_data)

In [10]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

accuracy_svm = accuracy_score(test_target, y_pred_svm)

print ('UBITname      = APURBAMA')
print ('Person Number = 50288705')
print("--------Linear SVM MNIST accuracy------------")
print(accuracy_svm*100)
print ('---------- Confusion Matrix--------------------')
print(confusion_matrix(test_target, y_pred_svm))

UBITname      = APURBAMA
Person Number = 50288705
--------Linear SVM accuracy------------
92.33
---------- Confusion Matrix--------------------
[[ 954    0    6    1    1    6    8    1    2    1]
 [   0 1114    2    5    0    1    1    1   11    0]
 [   8   13  946   13    6    3   12   11   15    5]
 [   5    5   20  931    1   20    3    7   15    3]
 [   2    0   14    1  933    0    3    4    1   24]
 [  15    5    8   44    6  781    7    2   21    3]
 [  10    5   14    0    8   20  899    0    2    0]
 [   1    9   21   17   13    0    0  943    4   20]
 [  13    6   17   32    8   28    9    9  842   10]
 [   7    6    6   15   42    7    1   25   10  890]]


In [13]:
usps_accuracy_svm = accuracy_score(USPS_Target, usps_pred_svm)
print("--------Linear SVM USPS accuracy------------")
print(usps_accuracy_svm*100)
print ('---------- Confusion Matrix--------------------')
print(confusion_matrix(USPS_Target, usps_pred_svm))

--------Linear SVM USPS accuracy------------
26.816340817040853
---------- Confusion Matrix--------------------
[[ 385    2  488  222  232  300   71  169   12  119]
 [  63  281  560  260  256  159   19  304   57   41]
 [ 158  103 1154  144   45  234   60   43   44   14]
 [  72   60  427  749   15  513    6   48   88   22]
 [  25   27  212  100  826  218   19  433   63   77]
 [  63   23  686  247   60  746   36   46   77   16]
 [ 180   19  914   90   81  206  445   36    3   26]
 [  26   77  198  723   70  301    7  490   73   35]
 [ 155   24  330  536  115  535   79   75  129   22]
 [  14   43  218  631  155  110    6  537  128  158]]
